config/routes.rb
DeltaChiWebsite::Application.routes.draw do

  root to: "statics#home"
  get "about" => "statics#home"
  get "home" => "statics#home"
  get "actives" => "statics#home"
  get "recruitment" => "statics#home"
  get "involvement" => "statics#home"
  get "donations" => "statics#home"
  get "contact" => "statics#home"
  get "login" => "statics#home"
  get "meet" => "statics#home"
  get "alumni" => "statics#home"
 

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/dynamics_controller.rb
class DynamicsController < ApplicationController

def meet
end

def alumni
end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def home
	end

	def about
	end

	def involvement
	end
	
	def recruitment
	end
	
	def donations
	end
	
	def contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/dynamics/alumni.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-8">
          <h1>Delta Chi Alumni <small>Welcome Home</small></h1>
        </div>
        <div class="col-sm-4">
          <h3 align="left">
          <div class="dropdown">
            <button class="btn dropdown-toggle btn-danger" type="button" id="dropdownMenu1" data-toggle="dropdown">Newsletters <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="http://issuu.com/drewwetherington/docs/wetherington_resume_jan21_2?e=10877032/6781549">Spring 2014</a></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Fall 2013</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Spring 2013</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Fall 2012</a></li>
            </ul>
          </div></h3>
        </div>
      </div>
      <ol class="breadcrumb" id="letter">
        <li><a href=".">Home</a></li>
        <li class="active">Alumni Home</li>
        <li><a href="#letter">Welcome Letter</a></li>
      </ol>
    </div>
  </div>
  <div class="col-sm-8">
    <h3>Message From The Webmaster</h3>
    <hr>
    <div class="row">
      <div class="col-sm-4">
        <img src="http://www.wired.com/images_blogs/threatlevel/2012/03/unclesam.jpeg" height="100%" width="100%"></img>
      </div>
      <div class="col-sm-8">
        Put text here
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="row">
      <div class="well well-sm">
        <div id="wufoo-qsieal904pybhk">
          Fill out my <a href="https://missourideltachi.wufoo.com/forms/qsieal904pybhk">online form</a>.
        </div>
      </div><!-- /well -->
    </div>
    <div class="row">
      <div class="well">
        <h4>Make A Donation<small> Every bit counts</small></h4>
        <p>Anything you contribute helps us towards fullfilling our goals and supporting our cause. If you would like to become a donator we have two types of donation routes.
        </p>
        <center><div class="input-group">
          <a href="donations.html"><button class="btn btn-large btn-danger" type="button">Donate Today</button></a>
        </div></center><!-- /input-group -->
      </div><!-- /well -->
    </div>
  </div>
</div><!-- /.container -->
<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/modern-business.js"></script>


<script type="text/javascript">var qsieal904pybhk;(function(d, t) {
          var s = d.createElement(t), options = {
          'userName':'missourideltachi', 
          'formHash':'qsieal904pybhk', 
          'autoResize':true,
          'height':'468',
          'async':true,
          'host':'wufoo.com',
          'header':'show', 
          'ssl':true};
          s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
          s.onload = s.onreadystatechange = function() {
          var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
          try { qsieal904pybhk = new WufooForm();qsieal904pybhk.initialize(options);qsieal904pybhk.display(); } catch (e) {}};
          var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
          })(document, 'script');</script>

app/views/dynamics/meet.html.erb
<div class="container" id="top">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="page-header" id="top">Meet The Actives</h1>
      <ol class="breadcrumb">
        <li><a href=".">Home</a></li>
        <li class="active">Meet Us</li>
      </ol>
    </div>
  </div><!-- /.row -->
  <div class="row">
    <div class="col-sm-12" id="main-area">
      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#exec" data-toggle="tab">Executives</a></li>
        <li><a href="#com" data-toggle="tab">Committee Heads</a></li>
        <li><a href="#all" data-toggle="tab">All Members</a></li>
      </ul>
      <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade in active" id="exec">
            <div class="row">
              <div class="col-sm-12">
                <div class="row">
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7459/13550783424_4c45e7cb86.jpg">
                    <center><h3>Jake Meyers<br><small>President <span class="label label-danger">A</span><br></small></h3></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7431/13550564683_d0a08f7d2b.jpg">
                    <center><h3>Tyler Gill<br><small>Vice President <span class="label label-danger">B</span></small></h3></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="">
                    <center><h3>Connor Bjornnes<br><small>Secretary <span class="label label-danger">C</span></small></h3></center>
                  </div>
                </div>      
                <div class="row">
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm4.staticflickr.com/3724/13550564823_a69ca4cc5a.jpg">
                    <center><h3>Zach Hadler<br><small>Treasurer <span class="label label-danger">D</span></small></h3></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm4.staticflickr.com/3680/13550565133_2c6c52b979.jpg">
                    <center><h3>Gian Wessel<br><small>Alumni <span class="label label-danger">E</span></small></h3></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm3.staticflickr.com/2891/13550463625_906d00e93f.jpg">
                    <center><h3>Calvin Rankin<br><small>Risk Manager <span class="label label-danger">F</span></small></h3></center>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- end of exec -->
          <div class="tab-pane fade" id="com">
            <div class="row">
              <div class="col-sm-12">
                <div class="row">
                  <div class="col-sm-4">
                    <img class="img-responsive" src="">
                    <center><h4>Austin Lewis<br><small>Merchandise</small></h4></center>
                  </div>

                  <div class="col-sm-4">
                    <img class="img-responsive" src="">
                    <center><h4>Andrew Carnahan<br><small>Brotherhood</small></h4></center>
                  </div>

                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7164/13550565473_086bd023e8.jpg">
                    <center><h4>Eric Jackson<br><small>Sports</small></h4></center>
                  </div>                
                </div>
                <div class="row">
                <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7215/13550463525_786c90c287.jpg">
                    <center><h4>Brian Strom<br><small>Ritual</small></h4></center>
                  </div> 
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm4.staticflickr.com/3767/13550781704_6110ebb4e7.jpg">
                    <center><h4>Danny Renner<br><small>Service</small></h4></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7310/13550783214_99bd03e43c.jpg">
                    <center><h4>Cole Lawson<br><small>Internal Philanthropy</small></h4></center>
                  </div>              
                </div>
                <div class="row">
                  <div class="col-sm-4">
                    <img class="img-responsive" src="">
                    <center><h4>Brock Scoville<br><small>External Philanthropy</small></h4></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="https://farm8.staticflickr.com/7021/13550464085_85e59b5a43.jpg">
                   <center><h4>Adam Joyce<br><small>Academics</small></h4></center>
                  </div>
                  <div class="col-sm-4">
                    <img class="img-responsive" src="">
                    <center><h4>Ryan Ebert<br><small>Banner Chair</small></h4></center>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- end of committee -->
          <div class="tab-pane fade" id="all">
            <div class="row">
              <div class="col-sm-8">
                <table class="table table-striped table-condensed">
                  <tbody>
                    <th colspan="2" id="be">Beta Epsilon &middot <a href="#top">Top <div class="glyphicon glyphicon-arrow-up"></div></a></th>
                    <tr><td>Japanese Johnson</td><td>Beta Epsilon</td></tr>
                      
                    <th colspan="2" id="bd">Beta Delta &middot <a href="#top">Top <div class="glyphicon glyphicon-arrow-up"></div></a></th>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    <tr><td>Drew Wetherington</td><td>Beta Delta</td></tr>
                    
                    <th colspan="2" id="bg">Beta Gamma &middot <a href="#top">Top <div class="glyphicon glyphicon-arrow-up"></div></a></th>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    <tr><td>John Doe</td><td>Beta Gamma</td></tr>
                    
                    <th colspan="2" id="bb">Beta Beta &middot <a href="#top">Top <div class="glyphicon glyphicon-arrow-up"></div></a></th>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>
                    <tr><td>John Doe</td><td>Beta Beta</td></tr>

                    <th colspan="2" id="ba">Beta Alpha &middot <a href="#top">Top <div class="glyphicon glyphicon-arrow-up"></div></a></th>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                    <tr><td>John Doe</td><td>Beta Alpha</td></tr>
                  </tbody>
                </table>
              </div>
              <div class="col-sm-4">
                  <div class="navbar-example">
                    <ul class="nav nav-pills nav-stacked fixed">
                      <li><a href="#be">Beta Epsilon</a></li>
                      <li><a href="#bd">Beta Delta</a></li>
                      <li><a href="#bg">Beta Gamma</a></li>
                      <li><a href="#bb">Beta Beta</a></li>
                      <li><a href="#ba">Beta Alpha</a></li>
                      <li><a href="#az">Alpha Zed</a></li>
                      <li><a href="#ap">Alpha Psi</a></li>
                      <li><a href="#ax">Alpha Xi</a></li>
                    </ul>
                  </div>
              </div>
          </div> <!-- end of all tab -->
        </div>
      </div>
    </div>
  </div><!-- row -->
  <hr>
</div><!-- /.container -->

<script>
  $('body').scrollspy({ target: '.navbar-example' })
})
</script>

<script>
$(document).ready(function() {  
 // check where the shoppingcart-div is  
 var offset = $("#comment").offset().top;  

 $(window).scroll(function () {  
   var scrollTop = $("#comment").scrollTop(); // check the visible top of the browser  


   if (scrollTop>50) {alert($("").scrollTop()+" px");
    $("#comment").addClass('fixed');  }
   else $("#comment").removeClass('fixed');  
  });  
}); 
</script>
<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/modern-business.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <link rel="shortcut icon" href="http://a0.twimg.com/profile_images/2403590114/s5j76ugc1q6pjwonk9jf.jpeg"/>
  <title>MU Delta Chi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=1024" name="viewport">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45687922-1', 'mudx.herokuapp.com');
  ga('send', 'pageview');
  </script>
</head>

<body>

<nav class="navbar-inner navbar  navbar-inverse navbar-fixed-top" role="navigation" name="top" id="navbargod">
  <div class="navbar-inner">
    <div class="container" style="width: auto;">
      <a class="navbar-brand active" href=".">MU Delta Chi</a>        
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <div class="nav navbar-nav navbar-left">
          
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "About", about_path %></li>
          <li><%=link_to "Meet Us", meet_path %></li>   
          <li><%=link_to "Recruitment", recruitment_path %></li>  
          <li><a href="http://mudeltachi.wordpress.com/" target="_blank">Blog <span class="glyphicon glyphicon-share-alt"><span></a></li>
          <li><%=link_to "Alumni", alumni_path %></li>
          <li><%=link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div><!-- /.container -->
  </div>
</nav>

<div>
  <ul class="list-unstyled icons-fixed">
    <li class="tooltip-social facebook-link"><a href="https://www.facebook.com/groups/missourideltachialumni/" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
    </li>
    <li class="tooltip-social twitter-link"><a href="https://twitter.com/MizzouDeltaChi" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
    </li>
    <li class="tooltip-social hq-link"><a href="http://www.deltachi.org/" data-toggle="tooltip" data-placement="top" title="Delta Chi HQ"><i class="fa fa-home fa-2x"></i></a>
    </li>
  </ul>
</div>
<%= yield %>
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p><center><a href="http://www.jimmyv.org/partners/delta-chi/"><img class="img" width="16px" src="https://farm8.staticflickr.com/7242/13550459665_b6b292d919.jpg"></a> &#149; &copy;2014 Missouri Delta Chi Fraternity</center></p>
    <!-- </div>
    <a href="#top" id="scroll-top-link" class="avia-font-entypo-fontello avia_pop_class">Top</a>
  </div> -->
</footer>
</body>
</html>

app/views/statics/actives.html.erb


    <div class="container">

      <div class="row">

        <div class="col-lg-12">
          <h1 class="page-header">Actives <small>Place To Submit Events</small></h1>
          <ol class="breadcrumb">
            <li><a href=".">Home</a></li>
            <li class="active">Actives</li>
          </ol>
        </div>

      </div>

      <div class="row">

        <div class="col-lg-8">
          <p>Make sure you're logged in. Once you are, a form will generate below for you to submit an event.</p>
          <p>Members will be able to sign up for events and will recieve text message reminders about the event.</p>
        </div>

        <div class="col-lg-4">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3>Events</h3>
            </div>
            <div class="panel-body">
              <div class="col-lg-6">
                <li><a href="#">Event 1</a>
              </div>
            <div class="col-lg-6">
             <a class="btn btn-danger" href="#">Join</a>
            </div>
            </div>
          </div>
        </div>
      </div>

    </div><!-- /.container -->

    <div class="container">

      <hr>
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/modern-business.js"></script>

app/views/statics/home.html copy.erb
    <!-- Full Page Image Header Area -->
    <div id="top" class="header">
      <div class="vert-text">
        
        <a href="#about" class="btn btn-danger-main btn-lg"><h2>See More of Missouri's Delta Chi</h2></a>
      </div>
    </div>
    <!-- /Full Page Image Header Area -->
  
    <!-- Intro -->
    <div id="about" class="intro">
      <div class="container">
        <div class="row">
          <br><br><br><br><br>
          <div class="col-md-6 col-md-offset-3 text-center" id="name">
            <br><br><br>
            <h1><img src="http://www.missourideltachi.com/resources/dx.jpg" height="36" width="36">  Delta Chi Fraternity  <image src="http://www.missourideltachi.com/resources/dx.jpg" height="36" width="36"></h1>
            <h3>Missouri Chapter</h3>
            <hr>
            <p class="lead">This website is for new members to discover, actives to communicate, and alumni to reconnect.</p>
          </div>
        </div>
      </div>
    </div>
    <!-- /Intro -->
  
    <!-- Services -->
    <div id="services" class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2></h2>
            <hr>  
          </div>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-2 text-center">
            <div class="service-item">
              <div class="btn btn-default btn-lg"><%=link_to "About", about_path %></div>
              <p>Want to know more about Dela Chi's membership, history, or contact us? Here's a good place to start!</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <div class="btn btn-default btn-lg"><%=link_to "Rush", recruitment_path %></div>
              <p>Interested in Delta Chi? Click here for contact info, FAQs, and the recruitment form. We look forward to meeting you soon!</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <div class="btn btn-default btn-lg"><%=link_to "Alumni", alumni_path %></div>
              <p>Glad to see you back around these parts. Want to schedule an event, tailgate, or a visit click here!</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <a href="http://mudeltachi.wordpress.com/" target="_blank"><div class="btn btn-default btn-lg">Blog <span class="glyphicon glyphicon-share-alt"></span></a></div>
              <p>Check out our latest events and news on our blog</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Services -->

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>

    <!-- Custom JavaScript for the Side Menu and Smooth Scrolling - Put in a custom JavaScript file to clean this up -->
    <script>
        $("#menu-close").click(function(e) {
            e.preventDefault();
            $("#sidebar-wrapper").toggleClass("active");
        });
    </script>
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#sidebar-wrapper").toggleClass("active");
        });
    </script>
    <script>
      $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
          if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
            || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
            if (target.length) {
              $('html,body').animate({
                scrollTop: target.offset().top
              }, 1000);
              return false;
            }
          }
        });
      });
    </script>
  </body>

</html>

app/views/statics/home.html.erb
<!-- Full Page Image Header Area -->
<!-- /Full Page Image Header Area -->
<div class="edge-container">
  <div class="row">
    <div class="col-sm-2">
      <img class="img-responsive" src="https://farm8.staticflickr.com/7113/13550769004_a20cf3216c.jpg">
      <img class="img-responsive" src="https://farm4.staticflickr.com/3777/13550769174_a4b590c2f6.jpg">
      <img class="img-responsive" src="https://farm4.staticflickr.com/3819/13550769954_226228bec2.jpg">
      <img class="img-responsive" src="https://farm8.staticflickr.com/7187/13550772934_636bc3fcce.jpg">
      <!--<img class="img-responsive" src="https://farm8.staticflickr.com/7242/13550459665_b6b292d919.jpg">-->
    </div>
    <div class="col-sm-8">
      <div id="about" class="intro">
        <div class="row">
          <div class="col-sm-12 text-center" id="name">
            <br><br><br>
            <h1><img src="http://www.missourideltachi.com/resources/dx.jpg" height="36" width="36">  Delta Chi Fraternity  <image src="http://www.missourideltachi.com/resources/dx.jpg" height="36" width="36"></h1>
            <h3>Site Under Construction</h3>
            <hr>
            <i><p class="lead">Redefining the social fraternity</p></i>
            <hr>
          </div>
        </div>
      </div>
      <!-- /Intro -->

      <!-- Services -->
      <div class="services">
        <div class="container">
          <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center">
              <h2></h2>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2 col-md-offset-2 text-center">
              <div class="service-item">
                <div class="btn btn-default btn-lg"><%=link_to "About", about_path %></div>
                <p>Want to know more about Dela Chi's membership, history, or contact us? Here's a good place to start!</p>
              </div>
            </div>
            <div class="col-md-2 text-center">
              <div class="service-item">
                <div class="btn btn-default btn-lg"><%=link_to "Rush", recruitment_path %></div>
                <p>Interested in Delta Chi? Click here for contact info, FAQs, and the recruitment form. We look forward to meeting you soon!</p>
              </div>
            </div>
            <div class="col-md-2 text-center">
              <div class="service-item">
                <div class="btn btn-default btn-lg"><%=link_to "Alumni", alumni_path %></div>
                <p>Glad to see you back around these parts. Want to schedule an event, tailgate, or a visit click here!</p>
              </div>
            </div>
            <div class="col-md-2 text-center">
              <div class="service-item">
                <a href="http://mudeltachi.wordpress.com/" target="_blank">
                <div class="btn btn-default btn-lg">Blog <span class="glyphicon glyphicon-share-alt"></span></a></div>
              </div> <!-- service item-->
              <p>Check out our latest events and news on our blog</p>
            </div> <!-- col-->
          </div> <!-- row-->
        </div> <!-- contain -->
      </div> <!-- services -->
    </div>
        <!-- /Services -->
    <div class="col-sm-2">
      <img class="img-responsive" src="https://farm8.staticflickr.com/7416/13550774784_ef93744c18.jpg">
      <img class="img-responsive" src="https://farm3.staticflickr.com/2905/13550450735_59fa3b7584.jpg">
      <img class="img-responsive" src="https://farm3.staticflickr.com/2877/13550771954_0323d48dc7.jpg">
      <!--<img class="img-responsive" src="https://farm8.staticflickr.com/7174/13550556703_d7137d08eb.jpg">-->
    </div> <!-- container -->
  </div>
</div>


    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>

    <!-- Custom JavaScript for the Side Menu and Smooth Scrolling - Put in a custom JavaScript file to clean this up -->

    <script>
    $("#menu-close").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
    });
    </script>
    <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
    });
    </script>
    <script>
    $(function() {
      $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
          || location.hostname == this.hostname) {

          var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
    });
    </script>
  </body>
  </html>